services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_DB: binance_futures
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
      - app-network

  mindsdb:
    image: mindsdb/mindsdb:latest
    environment:
      MINDSDB_DB_USER: mindsdb
      MINDSDB_DB_PASS: password
    ports:
      - "47334:47334"
      - "47335:47335"
    volumes:
      - mindsdb_data:/root/mindsdb_storage
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - timescaledb
      - mindsdb
    environment:
      DATABASE_URL: postgres://admin:password@timescaledb:5432/binance_futures
      MINDSDB_URL: http://mindsdb:47334
      CLAUDE_API_KEY: your_claude_api_key_here
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    networks:
      - app-network

volumes:
  timescaledb_data:
  mindsdb_data:

networks:
  app-network:
    driver: bridge